project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.home, name='home'),
    path('recipes/search/', views.search, name='search'),
    path('recipes/category/<int:category_id>/',
         views.category, name='category'),
    path('recipes/<int:id>/', views.recipe, name='recipe'),
]

recipes/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self) -> str:
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/cover/%Y/%m/%d/', blank=True, default='')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True, default=None
    )
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True
    )

    def __str__(self) -> str:
        return self.title

recipes/views.py
from django.shortcuts import get_list_or_404, get_object_or_404, render
from django.http.response import Http404
from django.db.models import Q

from . import models


def home(request):
    recipes = models.Recipe.objects.filter(is_published=True).order_by('-id')
    return render(request, 'recipes/pages/home.html', context={
        'recipes': recipes,
    })


def category(request, category_id):
    recipes = get_list_or_404(
        models.Recipe.objects.filter(
            category__id=category_id, is_published=True)
        .order_by('-id')
    )

    return render(request, 'recipes/pages/category.html', context={
        'recipes': recipes,
        'title': f'{recipes[0].category.name} - Category | '
    })


def recipe(request, id):

    recipe = get_object_or_404(
        models.Recipe.objects.filter(
            id=id, is_published=True)
    )

    return render(request, 'recipes/pages/recipeView.html', context={
        'recipe': recipe,
        'isDetailPage': True,
    })
    
def search(request):
    search_term = request.GET.get('q', '').strip()
    
    if not search_term:
        raise Http404()
    
    recipes = models.Recipe.objects.filter(
        Q(
            Q(title__icontains = search_term) |
            Q(description__icontains = search_term)
        ),
        is_published = True
    ).order_by('-id')
    
    return render(request, 'recipes/pages/search.html', context={
        'page_title': f'Search for "{search_term}" |',
        'search_term': search_term,
        'recipes': recipes
    })

recipes/templates/recipes/pages/category.html
{% extends 'global/base.html' %}

{% block title %}{{title}}{% endblock title %}

{% block content %}
<div class="mainContent mainContentList container">
    {% for recipe in recipes %}
        {% include 'recipes/partials/recipe.html' %}
    {% endfor %}
</div>
{% endblock content %}

recipes/templates/recipes/pages/home.html
{% extends 'global/base.html' %}

{% block title %}Home | {% endblock title %}

{% block content %}
<div class="mainContent mainContentList container">
    {% for recipe in recipes %}
        {% include 'recipes/partials/recipe.html' %}
    {% endfor %}
</div>
{% endblock content %}

recipes/templates/recipes/pages/recipeView.html
{% extends 'global/base.html' %}

{% block title %}{{recipe.title}} - {% endblock title %}

{% block content %}
<div class="mainContent mainContentDetail container">
    {% include 'recipes/partials/recipe.html' %}
</div>
{% endblock content %}

recipes/templates/recipes/pages/search.html
{% extends 'global/base.html' %}

{% block title %} {{page_title}} {% endblock title %}

{% block content %}
<div class="mainContent mainContentList container">
    {% for recipe in recipes %}
        {% include 'recipes/partials/recipe.html' %}
    {% empty %}
        <div class="center m-y">
            <h1>No recipes found here...</h1>
        </div>
    {% endfor %}       
</div>
{% endblock content %}

recipes/templates/recipes/partials/footer.html
<footer class="mainFooter">
    <div class="developer">
        <a href="https://github.com/Nulo0" target="_blank" rel="noreferrer noopener">By Daniel Pedro</a>
    </div>

    <div class="powered">
        <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>
</footer>

recipes/templates/recipes/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/fontawesome.min.css"
    integrity="sha512-giQeaPns4lQTBMRpOOHsYnGw1tGVzbAIHUyHRgn7+6FmiEgGGjaG0T2LZJmAPMzRCl+Cug0ItQ2xDZpTmEc+CQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/brands.min.css"
    integrity="sha512-G/T7HQJXSeNV7mKMXeJKlYNJ0jrs8RsWzYG7rVACye+qrcUhEAYKYzaa+VFy6eFzM2+/JT1Q+eqBbZFSHmJQew=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/solid.min.css"
    integrity="sha512-6mc0R607di/biCutMUtU9K7NtNewiGQzrvWX4bWTeqmljZdJrwYvKJtnhgR+Ryvj+NRJ8+NnnCM/biGqMe/iRA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

<link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">

recipes/templates/recipes/partials/header.html
<header class="mainHeaderContainer">
    <div class="mainHeader container">
        <h1>
            <a href="{% url 'recipes:home' %}" class="mainLogo">
                <i class="fas fa-utensils mainLogoIcon"></i>
                <span class="mainLogoText">Recipes</span>
            </a>
        </h1>
    </div>
</header>

recipes/templates/recipes/partials/recipe.html
<div class="recipe recipeListItem">

    <div class="recipeCover">
        {% if recipe.cover %}
        <a href="{% url 'recipes:recipe' recipe.id %}">
        <img src="{{ recipe.cover.url }}" alt="Temporário">
        </a>
        {% endif %}
    

        <div class="recipeTitleContainer">
            <a href="{% url 'recipes:recipe' recipe.id %}">
                <h2 class="recipeTitle">{{ recipe.title }}</h2>
            </a>
        </div>

        <div class="recipeAuthor">
            {% if recipe.author is not None %}
                <span class="recipeAuthorItem">
                    <i class="fas fa-user"></i>
                    {% if recipe.author.first_name %}
                        {{ recipe.author.first_name }} {{ recipe.author.last_name }}
                    {% else %}
                        {{recipe.author.username}}
                    {% endif %}      
                </span>
            {% endif %}
            <span class="recipeAuthorItem">
                <i class="fas fa-calendar-alt"></i>
                {{ recipe.created_at|date:"d/m/Y" }}
            </span>
            {% if recipe.category is not None %}
                <span class="recipeAuthorItem">
                    <a href="{% url 'recipes:category' recipe.category.id %}">
                        <i class="fas fa-layer-group"></i>
                        <span>{{ recipe.category.name }}</span>
                    </a>
                </span>
            {% endif %}
        </div>

        <div class="recipeContent">
            <p>{{ recipe.description }}</p>
        </div>

        <div class="recipeMetaContainer">
            <div class="recipeMeta recipePreparation">
                <h3 class="recipeMetaTitle"><i class="fas fa-stopwatch"></i> Preparo</h3>
                <div class="recipeMetaText">
                    {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
                </div>
            </div>
            <div class="recipeMeta recipeServings">
                <h3 class="recipeMetaTitle"><i class="fas fa-pizza-slice"></i> Porções</h3>
                <div class="recipeMetaText">
                    {{ recipe.servings }} {{ recipe.servings_unit }}
                </div>
            </div>
        </div>

        {% if isDetailPage is not True %}
            <footer class="recipeFooter">
                <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:recipe' recipe.id %}">
                    <i class="fas fa-eye"></i>
                    <span>ver mais...</span>
                </a>
            </footer>
        {% endif %}

        {% if isDetailPage is True %}
            <div class="preparationSteps">
                {% if recipe.preparation_steps_is_html is True %}
                    {{recipe.preparation_steps|safe}}
                {% else %}
                    {{recipe.preparation_steps|linebreaksbr}}
                {% endif %}   
            </div>
        {% endif %}

    </div>
</div>

recipes/templates/recipes/partials/search.html
<div class="searchContainer">
    <div class="container">
        <form action="{% url 'recipes:search' %}" method="get" class="searchForm">
            <input type="search" class="searchInput" name="q" value="{{search_term}}" required>
            <button type="submit" class="searchButton">
                <i class="fas fa-search"></i>
            </button>
        </form>
    </div>
</div>